import math

# Window constants
FPS = 60
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
WINDOW_TITLE = "agar.io"
DEBUG_TEXT_PADDING = 10
FONT_PATH = "Ubuntu-Bold.ttf"
FONT_DEBUG_SIZE = 16
FONT_CELLS_SIZE = 100
FONT_ANTI_ALIAS = True

# Camera constants
CAMERA_POS_FACTOR = 0.3
CAMERA_ZOOM_START = 0.2
CAMERA_ZOOM_FACTOR = 0.04
CAMERA_ZOOM_DEADBAND = 0.01

# Map constants
MAP_DIMENSIONS = 3000
MAP_SPACE = 40
MAP_LINE_WIDTH = 1
MAP_COLOR = (242, 251, 255)
MAP_GRID_COLOR = (182, 188, 190)

# Player constants
PLAYER_NAME = "John Cena"
PLAYER_SIZE_START = 100000
PLAYER_SIZE_MIN = 4000
PLAYER_SIZE_MAX = 5000000
PLAYER_SPEED = 4
PLAYER_ACCELERATION = 0.5
PLAYER_DEADBAND = 40
PLAYER_RADIUS_FACTOR = 0.1
PLAYER_EJECT_SIZE_MIN = 6000
PLAYER_EJECT_SIZE_LOSS = 2000
PLAYER_SPLIT_SPEED = 40.0
PLAYER_SPLIT_DECELERATION = 1.04
PLAYER_SPLIT_DECELERATION_DEADBAND = 0.1
PLAYER_SPLIT_SIZE_MIN = 6000
PLAYER_SPLIT_MAX = 16
PLAYER_PUSH_DEADBAND = 0.05
PLAYER_MERGE_TIME = FPS * 10
PLAYER_MERGE_SPEED = 0.4
PLAYER_MERGE_DEADBAND = 10
PLAYER_DECAY_RATE = 0.00001

# Cell constants
CELLS_RADIUS = 12
CELLS_SIZE = pow(CELLS_RADIUS, 2) * math.pi
CELLS_MAX = 500
CELLS_SPAWN_FREQUENCY = 20
CELLS_EJECT_RADIUS = 24
CELLS_EJECT_SIZE = pow(CELLS_EJECT_RADIUS, 2) * math.pi
CELLS_EJECT_SPEED = 16
CELLS_EJECT_DECELERATION = 0.97
CELLS_EJECT_DECELERATION_DEADBAND = 0.1

# Virus constants
VIRUS_RADIUS = 100
VIRUS_SIZE = pow(VIRUS_RADIUS, 2) * math.pi
VIRUS_MAX = 8
VIRUS_SPAWN_FREQUENCY = 0.01
VIRUS_SPLIT_SIZE = 8000
VIRUS_COLOR = (0, 255, 0)
VIRUS_OUTLINE_COLOR = (0, 234, 0)

OUTLINE_WIDTH = 8
BLACK = (0, 0, 0)
